http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 5000
  staleConnectionCheckEnabled: true

quartz:
  cron: 0 0/7 * * * ?
  urlList: [
    "https://blog.csdn.net/xiziyidi/article/details/104100642",
    "https://blog.csdn.net/xiziyidi/article/details/104099637",
    "https://blog.csdn.net/xiziyidi/article/details/104098264",
    "https://blog.csdn.net/xiziyidi/article/details/104093068",
    "https://blog.51cto.com/13851865/2467584",
    "https://blog.csdn.net/xiziyidi/article/details/104088036",
    "https://blog.51cto.com/13851865/2468436",
    "https://blog.csdn.net/xiziyidi/article/details/104087784",
    "https://blog.51cto.com/13851865/2467461",
    "https://blog.csdn.net/xiziyidi/article/details/104017647",
    "https://blog.csdn.net/xiziyidi/article/details/104009244",
    "https://blog.51cto.com/13851865/2466646",
    "https://blog.csdn.net/xiziyidi/article/details/104003181",
    "https://blog.csdn.net/xiziyidi/article/details/104003262",
    "https://blog.51cto.com/13851865/2458671",
    "https://blog.csdn.net/xiziyidi/article/details/103510370",
  ]
